buildscript {
    repositories {
        // These repositories are only for Gradle plugins, put any other repositories in the repository block further below
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}

apply plugin: 'org.spongepowered.mixin'

group = mod_group_id
version = mod_version

base {
    archivesName = "AE2-TangibleBookmarks-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    runs {
        // applies to all the run configs below
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }
        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            // example of overriding the workingDirectory set in configureEach above
            workingDirectory project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = "https://modmaven.dev"
        content {
            includeGroup "appeng"
            includeGroup "de.mari_023"
        }
    }
    //jei
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    //rei
    maven {
        url "https://maven.shedaniel.me"
    }

    //emi
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }

    //curseMaven
    maven {
        url "https://cursemaven.com"
    }
}

dependencies {
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0")) {
        jarJar.ranged(it, "[0.5.0,)")
    }

    minecraft fg.deobf("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    compileOnly 'org.jetbrains:annotations:24.1.0'

    implementation fg.deobf("appeng:appliedenergistics2-forge:${AE2_version}")
    implementation fg.deobf("me.myogoo:myotus:${Myotus_version}")

    compileOnly fg.deobf("org.appliedenergistics:guideme:${guideME_version}:api")
    runtimeOnly fg.deobf("org.appliedenergistics:guideme:${guideME_version}")


    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${JEI_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${JEI_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${JEI_version}")
    compileOnly fg.deobf("me.shedaniel:RoughlyEnoughItems-forge:${REI_version}")
    compileOnly fg.deobf("dev.emi:emi-forge:${EMI_version}")

    switch (project.itemListMod) {
        case "jei":
            runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${JEI_version}")
            runtimeOnly fg.deobf("curse.maven:ae2-jei-integration-1074338:5748513")
            break;
        case "rei":
            runtimeOnly fg.deobf("me.shedaniel:RoughlyEnoughItems-forge:${REI_version}")
            runtimeOnly fg.deobf("me.shedaniel.cloth:cloth-config-forge:11.1.118") // 버전은 프로젝트에 맞게 조절
            runtimeOnly fg.deobf("dev.architectury:architectury-forge:9.2.14")     // REI 필수 라이브러리
            break;
        case "emi":
            runtimeOnly fg.deobf("dev.emi:emi-forge:${EMI_version}")
            break;
        case "emjei":
            runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${JEI_version}")
            runtimeOnly fg.deobf("curse.maven:ae2-jei-integration-1074338:5748513")
            runtimeOnly fg.deobf("dev.emi:emi-forge:${EMI_version}")
            break;

    }
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                             forge_version       : forge_version, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
                             mod_authors         : mod_authors, mod_description: mod_description,]

    inputs.properties replaceProperties
    dependsOn tasks.named('compileJava')

    from(layout.buildDirectory.dir('tmp/compileJava')) {
        include "${mod_id}.refmap.json"
    }

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1", // We are version 1 of ourselves
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }

    // This is the preferred method to reobfuscate your jar file
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
