# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.100
neo_version_range=[26.1.2.99,26.2)
loader_version_range=[6,)
mod_id=ae2tb
mod_name=AE2 Tangible Bookmarks
mod_license=GNU LGPL 3.0
mod_version=26.0.0
java_version=25
mod_loader=neoforge
mod_version_type=release

mod_group_id=me.myogoo
mod_authors=NJoyShadow
mod_description=Integrates recipe-viewer bookmarks with Applied Energistics 2 terminals.

Myotus_version=26.0.0
AE2_version=26.1.10-beta
AE2_version_range=[26.1.10-beta,27)
JEI_version=29.33.0.87
JEI_version_range=[29.33.0.87,)
REI_version=26.1.819
AE2WTLib_version=26.1.1-beta

itemListMod=jei
enable_et=false
enable_ae2wt=true
